Repository vanessa-opensource/vanessa-runner, pull requests merged in 2019-10, with the labels that each got.

#321 Убрал "двойную" зависимость от пакета add + Добавил проверку команды xunit
  features/ПроверкаТестов.feature
  packagedef
  src/Классы/КомандаТестирование_xUnitFor1C.os
  src/Классы/КомандаТестированиеПоведения.os
  src/Модули/ОбщиеМетоды.os
  tests/fixtures/xdd_test/xdd_test.xml
  tests/fixtures/xdd_test/xdd_test/Ext/ObjectModule.bsl
Labels: technical debt, tests/features

#322 Создание нужных каталогов, в т.ч. и родительских, для ката… … 6a56109 …лого Allure и Junit
  features/ПроверкаСинтаксиса.feature
  packagedef
  src/Классы/КомандаПроверкаСинтаксиса.os
  src/Модули/ОбщиеМетоды.os
  tests/fixtures/cfbad/ConfigDumpInfo.xml
Labels: Enterprise support, technical debt

#302 Fix 300
  src/Классы/УпаковщикВнешнихОбработок.os
Labels: technical debt
