Repository vanessa-opensource/vanessa-runner, pull requests merged in 2019-12, with the labels that each got.

#329 Поддержка украинского языка для одного из клиентов
  epf/ЗакрытьПредприятие/ЗакрытьПредприятие/Forms/Форма/Ext/Form/Module.bsl
Labels: Enterprise support

#328 Исправлена ошибка записи пустого сообщения об ошибке в отчет junit
  src/Модули/ГенерацияОтчетов.os
Labels: technical debt

#333 Поддержка новых механизмов реструктуризации -v2/-v1 для команд init-dev и update-dev
  README.md
  features/ИнициализацияОкружения.feature
  features/ОбновлениеОкружения.feature
  src/Классы/КомандаИнициализацияОкружения.os
  src/Классы/КомандаОбновлениеКонфигурацииБД.os
  src/Классы/КомандаОбновлениеОкружения.os
  src/Модули/ОбщиеМетоды.os
Labels: docs, technical debt
