Repository vanessa-opensource/vanessa-runner, pull requests merged in 2020-02, with the labels that each got.

#342 #341. Исправление ошибки (некорректный путь сохранения собранного мех…
  src/Классы/УпаковщикВнешнихОбработок.os
Labels: bug

#345 При сборке внешнего механизма из исходников, итоговый файл сохраняется по пути, отличающемуся от требуемого (продолжение)
  features/СборкаОбработок.feature
  src/Классы/УпаковщикВнешнихОбработок.os
  src/Модули/ОбщиеМетоды.os
Labels: technical debt, tests/features

#335 Ошибка "Нет ошибок" при успешном прохождении синтаксического контроля
  src/Классы/КомандаПроверкаСинтаксиса.os
  src/Классы/КомандаТестированиеПоведения.os
  src/Модули/ГенерацияОтчетов.os
  src/Модули/ПараметрыСистемы.os
Labels: bug, technical debt

#346 Альтернативные имена переменных среды
  src/main.os
Labels: technical debt

#352 Исправлено необновление конфигурации ИБ при загрузке файла расширения
  src/Классы/МенеджерКонфигуратора.os
Labels: bug

#353 Выводить вменяемое сообщение об ошибках вместо длинного красного сообщения про результат работы
  features/ПроверкаВанесса.feature
  features/ПроверкаТестов.feature
  src/Классы/КомандаЗапуститьВРежимеПредприятия.os
  src/Классы/КомандаТестирование_xUnitFor1C.os
  src/Классы/КомандаТестированиеПоведения.os
  src/Классы/МенеджерКонфигуратора.os
  tests/fixtures/xUnitParams.json
  tests/fixtures/xdd_test/xdd_test.xml
Labels: Enterprise support, technical debt, tests/features

#354 Для команд запуска тестов и проверки поведения служебные сообщения, которые выдаются в форме 1С в окне сообщений, по умолчанию скрываются
  features/ПроверкаВанесса.feature
  src/Классы/КомандаТестирование_xUnitFor1C.os
  src/Классы/КомандаТестированиеПоведения.os
  src/Классы/МенеджерКонфигуратора.os
Labels: Enterprise support, technical debt, tests/features

#355 Команда для произвольного (интерактивного и автоматического) запуска в режиме Конфигуратор
  features/ЗапуститьКонфигуратор.feature
  src/Классы/КомандаЗапуститьКонфигуратор.os
  src/Классы/МенеджерКонфигуратора.os
  src/Модули/ПараметрыСистемы.os
Labels: technical debt
