Repository vanessa-opensource/vanessa-runner, pull requests merged in 2021-03, with the labels that each got.

#397 Добавил в остальные команды параметр --extension
  src/Классы/КомандаЗахватитьВХранилище.os
  src/Классы/КомандаКопироватьПользователейХранилища.os
  src/Классы/КомандаПоместитьВХранилище.os
  src/Классы/КомандаСоздатьПользователейХранилища.os
  src/Классы/КомандаСохранитьВерсиюХранилищаВФайл.os
  src/Классы/МенеджерКонфигуратора.os
Labels: Расширения 1С

#427 fix: Исправлена ошибка передачи пути к подсистеме запуска xUnit тестов
  src/Классы/КомандаТестирование_xUnitFor1C.os
Labels: tests/features, xUnitFor1C

#428 #264 Ошибка получения соединения и процесса
  src/Классы/КомандаУправлениеСеансами.os
Labels: bug
