Repository vanessa-opensource/vanessa-runner, pull requests merged in 2022-03, with the labels that each got.

#435 Добавлен учёт параметров ИБ при работе с пользователями хранилища - команды сохранения версии в файл, создание и копирование пользователей
  src/Классы/МенеджерКонфигуратора.os
Labels: Хранилище

#491 Исправлена некорректная передача параметра запуска
  src/Классы/МенеджерКонфигуратора.os
Labels: bug

#494 Команда xunit: Подставлять имя\пароль пользователя из данных подключения в настройки тест-клиента
  features/ПроверкаТестов.feature
  src/Классы/КомандаТестирование_xUnitFor1C.os
Labels: tests/features

#486 Добавлена возможность обновления расширения из хранилища
  src/Классы/КомандаОбновитьИзХранилища.os
Labels: Расширения 1С

#463 Добавлена возможность указания ИспользоватьОсновныеРолиДляВсехПользователей при загрузке расширений в режиме Предприятия
  epf/ЗагрузитьРасширениеВРежимеПредприятия/ЗагрузитьРасширениеВРежимеПредприятия/Forms/Форма/Ext/Form/Module.bsl
Labels: Расширения 1С
